name: Create federated identity
description: Establish federated identity credential between the AAD application and the service account issuer & subject

inputs:
  clusterName:
    description: 'name of AKS cluster'
    required: true
  tenant:
    description: 'Name of the tenant(client)'
    required: true
  resourceGroup:
    description: 'name of resource group where workspace is located'
    required: true

runs:
  using: "composite"
  steps:
    - name: Provision Workspace
      shell: bash
      run: |
        az aks show --resource-group ${{ inputs.resourceGroup }} --name ${{ inputs.clusterName }} --query 'oidcIssuerProfile.issuerUrl' -otsv
        spName=${{ inputs.tenant }}-sp
        serviceAccountName=${{ inputs.tenant }}-identity-sa
        # Output the OIDC issuer URL
        SERVICE_ACCOUNT_ISSUER=$(az aks show --resource-group ${{ inputs.resourceGroup }} --name ${{ inputs.clusterName }} --query 'oidcIssuerProfile.issuerUrl' -otsv)

        azwi serviceaccount create phase federated-identity \
          --service-account-issuer-url $SERVICE_ACCOUNT_ISSUER \
          --aad-application-name $spName \
          --service-account-namespace ${{ inputs.tenant }} \
          --service-account-name $serviceAccountName 
        